### ISSUE TITLE
Error when running in Visual Studio 2013

### ISSUE THREAD

**Issue by mehdi4467** [tgjones/slimshader#1]
Dear Sir
When I run this project in visual studio 2013 I get this error.
please see the picture:

http://img5013.photobox.co.uk/06795915b799473a8de27bb890d308f52d4b3d84491371332f40c07f4be1a574f9e5c28f.jpg

**Comment by tgjones** [comment]
You need to make sure the Startup Project is set to `SlimShader.Studio`.
